name: Swift

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    strategy:
        matrix:
            destination: ['platform=iOS Simulator,OS=13.1,name=iPhone 11']
    steps:
    - uses: actions/checkout@master
    - name: Build
        run: |
            xcodebuild clean -project GithubActionsTest.xcodeproj -scheme GithubActionsTest -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env:
           destination: ${{ matrix.destination }}

